# Requirement for root access
sudo: false
# Environment for building node-gyp
env:
  - CXX=g++-4.8
# Language
language: node_js
# Node Version
node_js:
  - "5.2.0"
# Addon for building node-gyp successfully
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
# Running Scripts
script:
  - npm run lint-ci
  - npm run sasslint-ci
  - npm run cover-ci
# Afer Success
after_success:
- npm run coveralls
